import os

DATABASE_URL = os.environ["DATABASE_URL"]
DISCORD_TOKEN = os.environ["DISCORD_TOKEN"]
MERRIAM_WEBSTER_KEY = os.environ["MERRIAM_WEBSTER_KEY"]
TWITTER_CONSUMER_KEY = os.environ["TWITTER_CONSUMER_KEY"]
TWITTER_CONSUMER_SECRET = os.environ["TWITTER_CONSUMER_SECRET"]
IMGUR_CLIENT_ID = os.environ["IMGUR_CLIENT_ID"]

EMBED_ACCENT_COLOUR = 0xF2F2F2  # White
